<a href="https://colab.research.google.com/github/mebre7/house-price-predictor-mlops/blob/colab_branch/notebooks/01_eda_and_baseline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploratory Data Analysis (EDA)
Exploratory Data Analysis (EDA) is a crucial step in the data analysis process that involves examining and visualizing data to uncover patterns, relationships, and insights. It helps in understanding the underlying structure of the data, identifying anomalies, and informing subsequent modeling decisions.

## 1. Load Data from PostgreSQL

In [50]:
from sqlalchemy import create_engine, text
import pandas as pd
import os
from dotenv import load_dotenv
from urllib.parse import quote_plus

In [51]:
load_dotenv()

DB_USER = os.getenv("DB_USER", "")
DB_PASSWORD = quote_plus(os.getenv("DB_PASSWORD", ""))
DB_HOST = os.getenv("DB_HOST", "")
DB_PORT = os.getenv("DB_PORT", "")
DB_NAME = os.getenv("DB_NAME", "")

# 2. Build SQLAlchemy connection string
DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
engine = create_engine(DATABASE_URL)
with engine.connect() as conn:
    df = pd.read_sql(
        text("SELECT * FROM housing_data"),
        conn
    )

df.head()

,Order,PID,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

### Import packages

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

**Change column names to snake_case for consistency and ease of use.**

In [53]:
df = df.rename(columns=lambda x: x.strip().replace(" ", "_").replace("-", "_"))

In [54]:
df

,Order,PID,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

## 2. Basic Shape & Types Audit

In [55]:
df.shape

(2930, 82)

-> $2930$ rows and $82$ features/columns

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS_SubClass      2930 non-null   int64
 3   MS_Zoning        2930 non-null   str
 4   Lot_Frontage     2440 non-null   float64
 5   Lot_Area         2930 non-null   int64
 6   Street           2930 non-null   str
 7   Alley            198 non-null    str
 8   Lot_Shape        2930 non-null   str
 9   Land_Contour     2930 non-null   str
 10  Utilities        2930 non-null   str
 11  Lot_Config       2930 non-null   str
 12  Land_Slope       2930 non-null   str
 13  Neighborhood     2930 non-null   str
 14  Condition_1      2930 non-null   str
 15  Condition_2      2930 non-null   str
 16  Bldg_Type        2930 non-null   str
 17  House_Style      2930 non-null   str
 18  Overall_Qual     2930 non-null   int64
 19  Overall_Cond     2930 non-null   int64
 20  Year_Built       2930 non-null   int64
 21  Year_Remod/Add   2930 non-null   int64
 22  Roof_Style       2930 non-null   str
 23  Roof_Matl        2930 non-null   str
 24  Exterior_1st     2930 non-null   str
 25  Exterior_2nd     2930 non-null   str
 26  Mas_Vnr_Type     1155 non-null   str
 27  Mas_Vnr_Area     2907 non-null   float64
 28  Exter_Qual       2930 non-null   str
 29  Exter_Cond       2930 non-null   str
 30  Foundation       2930 non-null   str
 31  Bsmt_Qual        2850 non-null   str
 32  Bsmt_Cond        2850 non-null   str
 33  Bsmt_Exposure    2847 non-null   str
 34  BsmtFin_Type_1   2850 non-null   str
 35  BsmtFin_SF_1     2929 non-null   float64
 36  BsmtFin_Type_2   2849 non-null   str
 37  BsmtFin_SF_2     2929 non-null   float64
 38  Bsmt_Unf_SF      2929 non-null   float64
 39  Total_Bsmt_SF    2929 non-null   float64
 40  Heating          2930 non-null   str
 41  Heating_QC       2930 non-null   str
 42  Central_Air      2930 non-null   str
 43  Electrical       2929 non-null   str
 44  1st_Flr_SF       2930 non-null   int64
 45  2nd_Flr_SF       2930 non-null   int64
 46  Low_Qual_Fin_SF  2930 non-null   int64
 47  Gr_Liv_Area      2930 non-null   int64
 48  Bsmt_Full_Bath   2928 non-null   float64
 49  Bsmt_Half_Bath   2928 non-null   float64
 50  Full_Bath        2930 non-null   int64
 51  Half_Bath        2930 non-null   int64
 52  Bedroom_AbvGr    2930 non-null   int64
 53  Kitchen_AbvGr    2930 non-null   int64
 54  Kitchen_Qual     2930 non-null   str
 55  TotRms_AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   str
 57  Fireplaces       2930 non-null   int64
 58  Fireplace_Qu     1508 non-null   str
 59  Garage_Type      2773 non-null   str
 60  Garage_Yr_Blt    2771 non-null   float64
 61  Garage_Finish    2771 non-null   str
 62  Garage_Cars      2929 non-null   float64
 63  Garage_Area      2929 non-null   float64
 64  Garage_Qual      2771 non-null   str
 65  Garage_Cond      2771 non-null   str
 66  Paved_Drive      2930 non-null   str
 67  Wood_Deck_SF     2930 non-null   int64
 68  Open_Porch_SF    2930 non-null   int64
 69  Enclosed_Porch   2930 non-null   int64
 70  3Ssn_Porch       2930 non-null   int64
 71  Screen_Porch     2930 non-null   int64
 72  Pool_Area        2930 non-null   int64
 73  Pool_QC          13 non-null     str
 74  Fence            572 non-null    str
 75  Misc_Feature     106 non-null    str
 76  Misc_Val         2930 non-null   int64
 77  Mo_Sold          2930 non-null   int64
 78  Yr_Sold          2930 non-null   int64
 79  Sale_Type        2930 non-null   str
 80  Sale_Condition   2930 non-null   str
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), str(43)
memory usage: 2.2 MB

Of 82 columns:
- Float: 11
- Integer: 28
- Object (string): 43

In [57]:
df.dtypes

Order               int64
PID                 int64
MS_SubClass         int64
MS_Zoning             str
Lot_Frontage      float64
                   ...
Mo_Sold             int64
Yr_Sold             int64
Sale_Type             str
Sale_Condition        str
SalePrice           int64
Length: 82, dtype: object

In [58]:
df.describe()

,Order,PID,MS_SubClass,Lot_Frontage,Lot_Area,Overall_Qual,Overall_Cond,Year_Built,Year_Remod/Add,Mas_Vnr_Area,...,Wood_Deck_SF,Open_Porch_SF,Enclosed_Porch,3Ssn_Porch,Screen_Porch,Pool_Area,Misc_Val,Mo_Sold,Yr_Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

Drop the following columns:

- `Order` as it is just a row number and does not provide any useful information for analysis.
- `PID` as it is a unique identifier for each property and does not contribute to the analysis.

In [59]:
PID = df['PID']
df = df.drop(['PID', 'Order'], axis=1)

In [61]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

### Numerical and Categorical Columns

In [178]:
# define numerical & categorical columns
numerical_features = df.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = df.select_dtypes(include=[object]).columns.tolist()
all_features = list(numerical_features) + list(categorical_features)

In [179]:
# print columns
print(f'{len(numerical_features)} numerical features: {numerical_features}')
print(f'\n{len(categorical_features)} categorical features: {categorical_features}')

37 numerical features: ['MS_SubClass', 'Lot_Frontage', 'Lot_Area', 'Overall_Qual', 'Overall_Cond', 'Year_Built', 'Year_Remod/Add', 'Mas_Vnr_Area', 'BsmtFin_SF_1', 'BsmtFin_SF_2', 'Bsmt_Unf_SF', 'Total_Bsmt_SF', '1st_Flr_SF', '2nd_Flr_SF', 'Low_Qual_Fin_SF', 'Gr_Liv_Area', 'Bsmt_Full_Bath', 'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr', 'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Fireplaces', 'Garage_Yr_Blt', 'Garage_Cars', 'Garage_Area', 'Wood_Deck_SF', 'Open_Porch_SF', 'Enclosed_Porch', '3Ssn_Porch', 'Screen_Porch', 'Pool_Area', 'Misc_Val', 'Mo_Sold', 'Yr_Sold', 'SalePrice']

43 categorical features: ['MS_Zoning', 'Street', 'Alley', 'Lot_Shape', 'Land_Contour', 'Utilities', 'Lot_Config', 'Land_Slope', 'Neighborhood', 'Condition_1', 'Condition_2', 'Bldg_Type', 'House_Style', 'Roof_Style', 'Roof_Matl', 'Exterior_1st', 'Exterior_2nd', 'Mas_Vnr_Type', 'Exter_Qual', 'Exter_Cond', 'Foundation', 'Bsmt_Qual', 'Bsmt_Cond', 'Bsmt_Exposure', 'BsmtFin_Type_1', 'BsmtFin_Type_2', 'Heating', 'Heating_QC', 'Central_Air', 'Electrical', 'Kitchen_Qual', 'Functional', 'Fireplace_Qu', 'Garage_Type', 'Garage_Finish', 'Garage_Qual', 'Garage_Cond', 'Paved_Drive', 'Pool_QC', 'Fence', 'Misc_Feature', 'Sale_Type', 'Sale_Condition']

There are:
- **37** numeric features
- **43** categorical features

#### Frequency of each column
- Proportion of individual values in each column

In [116]:
for col in categorical_features:
  print(df[col].value_counts(normalize=True) * 100)
  print(f"\n----------------------------------")

MS_Zoning
RL         77.576792
RM         15.767918
FV          4.744027
RH          0.921502
C (all)     0.853242
I (all)     0.068259
A (agr)     0.068259
Name: proportion, dtype: float64

----------------------------------
Street
Pave    99.590444
Grvl     0.409556
Name: proportion, dtype: float64

----------------------------------
Alley
Grvl    60.606061
Pave    39.393939
Name: proportion, dtype: float64

----------------------------------
Lot_Shape
Reg    63.447099
IR1    33.412969
IR2     2.593857
IR3     0.546075
Name: proportion, dtype: float64

----------------------------------
Land_Contour
Lvl    89.863481
HLS     4.095563
Bnk     3.993174
Low     2.047782
Name: proportion, dtype: float64

----------------------------------
Utilities
AllPub    99.897611
NoSewr     0.068259
NoSeWa     0.034130
Name: proportion, dtype: float64

----------------------------------
Lot_Config
Inside     73.037543
Corner     17.440273
CulDSac     6.143345
FR2         2.901024
FR3         0.477816
Name: proportion, dtype: float64

----------------------------------
Land_Slope
Gtl    95.187713
Mod     4.266212
Sev     0.546075
Name: proportion, dtype: float64

----------------------------------
Neighborhood
NAmes      15.119454
CollgCr     9.112628
OldTown     8.156997
Edwards     6.621160
Somerst     6.211604
NridgHt     5.665529
Gilbert     5.631399
Sawyer      5.153584
NWAmes      4.470990
SawyerW     4.266212
Mitchel     3.890785
BrkSide     3.686007
Crawfor     3.515358
IDOTRR      3.174061
Timber      2.457338
NoRidge     2.423208
StoneBr     1.740614
SWISU       1.638225
ClearCr     1.501706
MeadowV     1.262799
BrDale      1.023891
Blmngtn     0.955631
Veenker     0.819113
NPkVill     0.784983
Blueste     0.341297
Greens      0.273038
GrnHill     0.068259
Landmrk     0.034130
Name: proportion, dtype: float64

----------------------------------
Condition_1
Norm      86.075085
Feedr      5.597270
Artery     3.139932
RRAn       1.706485
PosN       1.331058
RRAe       0.955631
PosA       0.682594
RRNn       0.307167
RRNe       0.204778
Name: proportion, dtype: float64

----------------------------------
Condition_2
Norm      98.976109
Feedr      0.443686
Artery     0.170648
PosA       0.136519
PosN       0.136519
RRNn       0.068259
RRAe       0.034130
RRAn       0.034130
Name: proportion, dtype: float64

----------------------------------
Bldg_Type
1Fam      82.764505
TwnhsE     7.952218
Duplex     3.720137
Twnhs      3.447099
2fmCon     2.116041
Name: proportion, dtype: float64

----------------------------------
House_Style
1Story    50.546075
2Story    29.795222
1.5Fin    10.716724
SLvl       4.368601
SFoyer     2.832765
2.5Unf     0.819113
1.5Unf     0.648464
2.5Fin     0.273038
Name: proportion, dtype: float64

----------------------------------
Roof_Style
Gable      79.215017
Hip        18.805461
Gambrel     0.750853
Flat        0.682594
Mansard     0.375427
Shed        0.170648
Name: proportion, dtype: float64

----------------------------------
Roof_Matl
CompShg    98.532423
Tar&Grv     0.784983
WdShake     0.307167
WdShngl     0.238908
Membran     0.034130
ClyTile     0.034130
Roll        0.034130
Metal       0.034130
Name: proportion, dtype: float64

----------------------------------
Exterior_1st
VinylSd    35.017065
MetalSd    15.358362
HdBoard    15.085324
Wd Sdng    14.334471
Plywood     7.542662
CemntBd     4.300341
BrkFace     3.003413
WdShing     1.911263
AsbShng     1.501706
Stucco      1.467577
BrkComm     0.204778
AsphShn     0.068259
CBlock      0.068259
Stone       0.068259
PreCast     0.034130
ImStucc     0.034130
Name: proportion, dtype: float64

----------------------------------
Exterior_2nd
VinylSd    34.641638
MetalSd    15.255973
HdBoard    13.856655
Wd Sdng    13.549488
Plywood     9.351536
CmentBd     4.300341
Wd Shng     2.764505
BrkFace     1.604096
Stucco      1.604096
AsbShng     1.296928
Brk Cmn     0.750853
ImStucc     0.511945
Stone       0.204778
AsphShn     0.136519
CBlock      0.102389
PreCast     0.034130
Other       0.034130
Name: proportion, dtype: float64

----------------------------------
Mas_Vnr_Type
BrkFace    76.190476
Stone      21.558442
BrkCmn      2.164502
CBlock      0.086580
Name: proportion, dtype: float64

----------------------------------
Exter_Qual
TA    61.399317
Gd    33.754266
Ex     3.651877
Fa     1.194539
Name: proportion, dtype: float64

----------------------------------
Exter_Cond
TA    86.996587
Gd    10.204778
Fa     2.286689
Ex     0.409556
Po     0.102389
Name: proportion, dtype: float64

----------------------------------
Foundation
PConc     44.709898
CBlock    42.457338
BrkTil    10.614334
Slab       1.672355
Stone      0.375427
Wood       0.170648
Name: proportion, dtype: float64

----------------------------------
Bsmt_Qual
TA    45.017544
Gd    42.771930
Ex     9.052632
Fa     3.087719
Po     0.070175
Name: proportion, dtype: float64

----------------------------------
Bsmt_Cond
TA    91.789474
Gd     4.280702
Fa     3.649123
Po     0.175439
Ex     0.105263
Name: proportion, dtype: float64

----------------------------------
Bsmt_Exposure
No    66.947664
Av    14.682122
Gd     9.975413
Mn     8.394802
Name: proportion, dtype: float64

----------------------------------
BsmtFin_Type_1
GLQ    30.140351
Unf    29.859649
ALQ    15.052632
Rec    10.105263
BLQ     9.438596
LwQ     5.403509
Name: proportion, dtype: float64

----------------------------------
BsmtFin_Type_2
Unf    87.714988
Rec     3.720604
LwQ     3.123903
BLQ     2.386802
ALQ     1.860302
GLQ     1.193401
Name: proportion, dtype: float64

----------------------------------
Heating
GasA     98.464164
GasW      0.921502
Grav      0.307167
Wall      0.204778
OthW      0.068259
Floor     0.034130
Name: proportion, dtype: float64

----------------------------------
Heating_QC
Ex    51.023891
TA    29.488055
Gd    16.245734
Fa     3.139932
Po     0.102389
Name: proportion, dtype: float64

----------------------------------
Central_Air
Y    93.31058
N     6.68942
Name: proportion, dtype: float64

----------------------------------
Electrical
SBrkr    91.567088
FuseA     6.418573
FuseF     1.707067
FuseP     0.273131
Mix       0.034141
Name: proportion, dtype: float64

----------------------------------
Kitchen_Qual
TA    50.989761
Gd    39.590444
Ex     6.996587
Fa     2.389078
Po     0.034130
Name: proportion, dtype: float64

----------------------------------
Functional
Typ     93.105802
Min2     2.389078
Min1     2.218430
Mod      1.194539
Maj1     0.648464
Maj2     0.307167
Sev      0.068259
Sal      0.068259
Name: proportion, dtype: float64

----------------------------------
Fireplace_Qu
Gd    49.336870
TA    39.787798
Fa     4.973475
Po     3.050398
Ex     2.851459
Name: proportion, dtype: float64

----------------------------------
Garage_Type
Attchd     62.423368
Detchd     28.200505
BuiltIn     6.707537
Basment     1.298233
2Types      0.829427
CarPort     0.540930
Name: proportion, dtype: float64

----------------------------------
Garage_Finish
Unf    44.424396
RFn    29.303501
Fin    26.272104
Name: proportion, dtype: float64

----------------------------------
Garage_Qual
TA    94.370263
Fa     4.474919
Gd     0.866113
Po     0.180440
Ex     0.108264
Name: proportion, dtype: float64

----------------------------------
Garage_Cond
TA    96.174666
Fa     2.670516
Gd     0.541321
Po     0.505233
Ex     0.108264
Name: proportion, dtype: float64

----------------------------------
Paved_Drive
Y    90.511945
N     7.372014
P     2.116041
Name: proportion, dtype: float64

----------------------------------
Pool_QC
Ex    30.769231
Gd    30.769231
TA    23.076923
Fa    15.384615
Name: proportion, dtype: float64

----------------------------------
Fence
MnPrv    57.692308
GdPrv    20.629371
GdWo     19.580420
MnWw      2.097902
Name: proportion, dtype: float64

----------------------------------
Misc_Feature
Shed    89.622642
Gar2     4.716981
Othr     3.773585
Elev     0.943396
TenC     0.943396
Name: proportion, dtype: float64

----------------------------------
Sale_Type
WD       86.552901
New       8.156997
COD       2.969283
ConLD     0.887372
CWD       0.409556
ConLI     0.307167
ConLw     0.273038
Oth       0.238908
Con       0.170648
VWD       0.034130
Name: proportion, dtype: float64

----------------------------------
Sale_Condition
Normal     82.354949
Partial     8.361775
Abnorml     6.484642
Family      1.569966
Alloca      0.819113
AdjLand     0.409556
Name: proportion, dtype: float64

----------------------------------

## 3. Missing Value Analysis

In [117]:
df.isnull().sum().sort_values(ascending=False)

Pool_QC           2917
Misc_Feature      2824
Alley             2732
Fence             2358
Mas_Vnr_Type      1775
                  ...
Mo_Sold              0
Yr_Sold              0
Sale_Type            0
Sale_Condition       0
SalePrice            0
Length: 80, dtype: int64

In [118]:
# count the number of rows in the dataframe in each column that have null values
df.isnull().count()

MS_SubClass       2930
MS_Zoning         2930
Lot_Frontage      2930
Lot_Area          2930
Street            2930
                  ...
Mo_Sold           2930
Yr_Sold           2930
Sale_Type         2930
Sale_Condition    2930
SalePrice         2930
Length: 80, dtype: int64

**Count the number of missing values in each column and percentage of missing values in each column. This helps to identify which columns have a significant amount of missing data and may require imputation or removal.**

In [119]:
count = df.isnull().sum().sort_values(ascending=False)
percentage = ((df.isnull().sum() / df.isnull().count()) * 100).sort_values(ascending=False)
null_values = pd.concat([count, percentage], axis=1, keys=['Count', 'Percentage'])

In [120]:
null_values.head(n=28)

                Count  Percentage
Pool_QC          2917   99.556314
Misc_Feature     2824   96.382253
Alley            2732   93.242321
Fence            2358   80.477816
Mas_Vnr_Type     1775   60.580205
Fireplace_Qu     1422   48.532423
Lot_Frontage      490   16.723549
Garage_Yr_Blt     159    5.426621
Garage_Qual       159    5.426621
Garage_Cond       159    5.426621
Garage_Finish     159    5.426621
Garage_Type       157    5.358362
Bsmt_Exposure      83    2.832765
BsmtFin_Type_2     81    2.764505
Bsmt_Qual          80    2.730375
BsmtFin_Type_1     80    2.730375
Bsmt_Cond          80    2.730375
Mas_Vnr_Area       23    0.784983
Bsmt_Full_Bath      2    0.068259
Bsmt_Half_Bath      2    0.068259
BsmtFin_SF_2        1    0.034130
Garage_Area         1    0.034130
Total_Bsmt_SF       1    0.034130
BsmtFin_SF_1        1    0.034130
Electrical          1    0.034130
Bsmt_Unf_SF         1    0.034130
Garage_Cars         1    0.034130
Lot_Shape           0    0.000000

**Insights**:
- The `PoolQC` column has the highest percentage of missing values (99.55%), followed by `MiscFeature` (96.38%) and `Alley` (93.24%). These columns may require special attention for imputation or removal.

**How many columns have missing values?**

In [121]:
# how many columns have missing values?
columns_with_missing_values = null_values[null_values['Count'] > 0].shape[0]
columns_with_missing_values

27

> There are $27$ columns with missing values. Remaining $53$ columns have no missing values.

**Any duplicated rows?**

In [122]:
df.duplicated().sum()

np.int64(0)

> No duplicated rows were found in the dataset, indicating that each row represents a unique property listing.

## 4. Feature Classification

1. **Categorical Features**: Columns that represent distinct categories or groups.
2. **Numerical Features**: Columns that represent numbers. These are further divided into continuous and discrete:
   - **Discrete Features**: Numerical values that are countable and finite.
   - **Continuous Features**: Numerical values that can take any value.
3. **Temporal Features**: Features that represent time.

In [123]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

**1. Numerical features**

In [124]:
# Numerical features
numerical_features = numerical_features
# Categorical features
categorical_features = categorical_features
# All features
all_features = numerical_features + categorical_features

In [125]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [126]:
# Discrete features
discrete_num_features = ['MS_SubClass', 'Overall_Qual', 'Overall_Cond', 'Bsmt_Full_Bath', 'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr', 'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Fireplaces', 'Garage_Cars']
discrete_num_features

['MS_SubClass',
 'Overall_Qual',
 'Overall_Cond',
 'Bsmt_Full_Bath',
 'Bsmt_Half_Bath',
 'Full_Bath',
 'Half_Bath',
 'Bedroom_AbvGr',
 'Kitchen_AbvGr',
 'TotRms_AbvGrd',
 'Fireplaces',
 'Garage_Cars']

In [149]:
# Add discrete features to categorical features list
categorical_features_all = list(set(categorical_features + discrete_num_features))

> Add discrete features to categorical features list. This is done because discrete features, while numerical, often represent categories (e.g., number of bedrooms) and can be treated as categorical for analysis purposes.

**2. Categorical features**

In [151]:
categorical_features_all

['Condition_1',
 'MS_SubClass',
 'Bsmt_Exposure',
 'Paved_Drive',
 'Electrical',
 'Exter_Qual',
 'Sale_Condition',
 'Mas_Vnr_Type',
 'Garage_Finish',
 'Bsmt_Cond',
 'Street',
 'Bsmt_Full_Bath',
 'Neighborhood',
 'Foundation',
 'Heating',
 'Functional',
 'Bedroom_AbvGr',
 'Roof_Style',
 'Roof_Matl',
 'House_Style',
 'Pool_QC',
 'Sale_Type',
 'Kitchen_Qual',
 'Lot_Config',
 'Garage_Cars',
 'Half_Bath',
 'Overall_Qual',
 'Bsmt_Qual',
 'Land_Slope',
 'Fence',
 'Overall_Cond',
 'Bldg_Type',
 'MS_Zoning',
 'Condition_2',
 'Fireplaces',
 'BsmtFin_Type_1',
 'Garage_Cond',
 'Bsmt_Half_Bath',
 'BsmtFin_Type_2',
 'Garage_Qual',
 'TotRms_AbvGrd',
 'Central_Air',
 'Exterior_2nd',
 'Garage_Type',
 'Fireplace_Qu',
 'Lot_Shape',
 'Exterior_1st',
 'Kitchen_AbvGr',
 'Heating_QC',
 'Alley',
 'Misc_Feature',
 'Exter_Cond',
 'Full_Bath',
 'Utilities',
 'Land_Contour']

In [152]:
# Continuous features
continuous_num_features = list(set(numerical_features) - set(discrete_num_features))
continuous_num_features

['Year_Remod/Add',
 '1st_Flr_SF',
 'Bsmt_Unf_SF',
 'Wood_Deck_SF',
 'Year_Built',
 '3Ssn_Porch',
 '2nd_Flr_SF',
 'Low_Qual_Fin_SF',
 'Gr_Liv_Area',
 'Open_Porch_SF',
 'Yr_Sold',
 'BsmtFin_SF_1',
 'Mo_Sold',
 'Total_Bsmt_SF',
 'BsmtFin_SF_2',
 'Pool_Area',
 'Lot_Frontage',
 'Garage_Yr_Blt',
 'Screen_Porch',
 'Enclosed_Porch',
 'Garage_Area',
 'Lot_Area',
 'Mas_Vnr_Area',
 'SalePrice',
 'Misc_Val']

In [153]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [154]:
date_year = ['Year_Built', 'Year_Remod/Add', 'Garage_Yr_Blt', 'Yr_Sold', ]
date_month = ['Mo_Sold']

In [155]:
for col in date_year:
    df[col] = pd.to_datetime(df[col], format='%Y').dt.year

for col in date_month:
    df[col] = pd.to_datetime(df[col], format='%m').dt.month

In [156]:
# Temporal features
temporal_features = date_year + date_month
temporal_features

['Year_Built', 'Year_Remod/Add', 'Garage_Yr_Blt', 'Yr_Sold', 'Mo_Sold']

1. Numerical features

In [157]:
discrete_num_features = discrete_num_features
continuous_num_features = continuous_num_features

In [158]:
print(f"{len(discrete_num_features)} discrete numerical features: {discrete_num_features}\n")
print(f"{len(continuous_num_features)} continuous numerical features: {continuous_num_features}")

12 discrete numerical features: ['MS_SubClass', 'Overall_Qual', 'Overall_Cond', 'Bsmt_Full_Bath', 'Bsmt_Half_Bath', 'Full_Bath', 'Half_Bath', 'Bedroom_AbvGr', 'Kitchen_AbvGr', 'TotRms_AbvGrd', 'Fireplaces', 'Garage_Cars']

25 continuous numerical features: ['Year_Remod/Add', '1st_Flr_SF', 'Bsmt_Unf_SF', 'Wood_Deck_SF', 'Year_Built', '3Ssn_Porch', '2nd_Flr_SF', 'Low_Qual_Fin_SF', 'Gr_Liv_Area', 'Open_Porch_SF', 'Yr_Sold', 'BsmtFin_SF_1', 'Mo_Sold', 'Total_Bsmt_SF', 'BsmtFin_SF_2', 'Pool_Area', 'Lot_Frontage', 'Garage_Yr_Blt', 'Screen_Porch', 'Enclosed_Porch', 'Garage_Area', 'Lot_Area', 'Mas_Vnr_Area', 'SalePrice', 'Misc_Val']

2. Categorical features

In [159]:
categorical_features_all = categorical_features_all

In [160]:
print(f"{len(categorical_features_all)} categorical features: {categorical_features_all}")

55 categorical features: ['Condition_1', 'MS_SubClass', 'Bsmt_Exposure', 'Paved_Drive', 'Electrical', 'Exter_Qual', 'Sale_Condition', 'Mas_Vnr_Type', 'Garage_Finish', 'Bsmt_Cond', 'Street', 'Bsmt_Full_Bath', 'Neighborhood', 'Foundation', 'Heating', 'Functional', 'Bedroom_AbvGr', 'Roof_Style', 'Roof_Matl', 'House_Style', 'Pool_QC', 'Sale_Type', 'Kitchen_Qual', 'Lot_Config', 'Garage_Cars', 'Half_Bath', 'Overall_Qual', 'Bsmt_Qual', 'Land_Slope', 'Fence', 'Overall_Cond', 'Bldg_Type', 'MS_Zoning', 'Condition_2', 'Fireplaces', 'BsmtFin_Type_1', 'Garage_Cond', 'Bsmt_Half_Bath', 'BsmtFin_Type_2', 'Garage_Qual', 'TotRms_AbvGrd', 'Central_Air', 'Exterior_2nd', 'Garage_Type', 'Fireplace_Qu', 'Lot_Shape', 'Exterior_1st', 'Kitchen_AbvGr', 'Heating_QC', 'Alley', 'Misc_Feature', 'Exter_Cond', 'Full_Bath', 'Utilities', 'Land_Contour']

3. Temporal features

In [161]:
temporal_features = temporal_features

In [162]:
print(f"{len(temporal_features)} temporal features: {temporal_features}")

5 temporal features: ['Year_Built', 'Year_Remod/Add', 'Garage_Yr_Blt', 'Yr_Sold', 'Mo_Sold']

In [163]:
print(f"Number of numerical features: {len(numerical_features)}")
print(f"Number of categorical features: {len(categorical_features_all)}")
print(f"Number of continuous numerical features: {len(continuous_num_features)}")
print(f"Number of discrete numerical features: {len(discrete_num_features)}")
print(f"Number of all features: {len(all_features)}")

Number of numerical features: 37
Number of categorical features: 55
Number of continuous numerical features: 25
Number of discrete numerical features: 12
Number of all features: 80

In [166]:
df[numerical_features].info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   MS_SubClass      2930 non-null   int64
 1   Lot_Frontage     2440 non-null   float64
 2   Lot_Area         2930 non-null   int64
 3   Overall_Qual     2930 non-null   int64
 4   Overall_Cond     2930 non-null   int64
 5   Year_Built       2930 non-null   int32
 6   Year_Remod/Add   2930 non-null   int32
 7   Mas_Vnr_Area     2907 non-null   float64
 8   BsmtFin_SF_1     2929 non-null   float64
 9   BsmtFin_SF_2     2929 non-null   float64
 10  Bsmt_Unf_SF      2929 non-null   float64
 11  Total_Bsmt_SF    2929 non-null   float64
 12  1st_Flr_SF       2930 non-null   int64
 13  2nd_Flr_SF       2930 non-null   int64
 14  Low_Qual_Fin_SF  2930 non-null   int64
 15  Gr_Liv_Area      2930 non-null   int64
 16  Bsmt_Full_Bath   2928 non-null   float64
 17  Bsmt_Half_Bath   2928 non-null   float64
 18  Full_Bath        2930 non-null   int64
 19  Half_Bath        2930 non-null   int64
 20  Bedroom_AbvGr    2930 non-null   int64
 21  Kitchen_AbvGr    2930 non-null   int64
 22  TotRms_AbvGrd    2930 non-null   int64
 23  Fireplaces       2930 non-null   int64
 24  Garage_Yr_Blt    2771 non-null   float64
 25  Garage_Cars      2929 non-null   float64
 26  Garage_Area      2929 non-null   float64
 27  Wood_Deck_SF     2930 non-null   int64
 28  Open_Porch_SF    2930 non-null   int64
 29  Enclosed_Porch   2930 non-null   int64
 30  3Ssn_Porch       2930 non-null   int64
 31  Screen_Porch     2930 non-null   int64
 32  Pool_Area        2930 non-null   int64
 33  Misc_Val         2930 non-null   int64
 34  Mo_Sold          2930 non-null   int32
 35  Yr_Sold          2930 non-null   int32
 36  SalePrice        2930 non-null   int64
dtypes: float64(11), int32(4), int64(22)
memory usage: 801.3 KB

In [181]:
df[categorical_features_all].info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 55 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Condition_1     2930 non-null   category
 1   MS_SubClass     2930 non-null   category
 2   Bsmt_Exposure   2847 non-null   category
 3   Paved_Drive     2930 non-null   category
 4   Electrical      2929 non-null   category
 5   Exter_Qual      2930 non-null   category
 6   Sale_Condition  2930 non-null   category
 7   Mas_Vnr_Type    1155 non-null   category
 8   Garage_Finish   2771 non-null   category
 9   Bsmt_Cond       2850 non-null   category
 10  Street          2930 non-null   category
 11  Bsmt_Full_Bath  2928 non-null   category
 12  Neighborhood    2930 non-null   category
 13  Foundation      2930 non-null   category
 14  Heating         2930 non-null   category
 15  Functional      2930 non-null   category
 16  Bedroom_AbvGr   2930 non-null   category
 17  Roof_Style      2930 non-null   category
 18  Roof_Matl       2930 non-null   category
 19  House_Style     2930 non-null   category
 20  Pool_QC         13 non-null     category
 21  Sale_Type       2930 non-null   category
 22  Kitchen_Qual    2930 non-null   category
 23  Lot_Config      2930 non-null   category
 24  Garage_Cars     2929 non-null   category
 25  Half_Bath       2930 non-null   category
 26  Overall_Qual    2930 non-null   category
 27  Bsmt_Qual       2850 non-null   category
 28  Land_Slope      2930 non-null   category
 29  Fence           572 non-null    category
 30  Overall_Cond    2930 non-null   category
 31  Bldg_Type       2930 non-null   category
 32  MS_Zoning       2930 non-null   category
 33  Condition_2     2930 non-null   category
 34  Fireplaces      2930 non-null   category
 35  BsmtFin_Type_1  2850 non-null   category
 36  Garage_Cond     2771 non-null   category
 37  Bsmt_Half_Bath  2928 non-null   category
 38  BsmtFin_Type_2  2849 non-null   category
 39  Garage_Qual     2771 non-null   category
 40  TotRms_AbvGrd   2930 non-null   category
 41  Central_Air     2930 non-null   category
 42  Exterior_2nd    2930 non-null   category
 43  Garage_Type     2773 non-null   category
 44  Fireplace_Qu    1508 non-null   category
 45  Lot_Shape       2930 non-null   category
 46  Exterior_1st    2930 non-null   category
 47  Kitchen_AbvGr   2930 non-null   category
 48  Heating_QC      2930 non-null   category
 49  Alley           198 non-null    category
 50  Misc_Feature    106 non-null    category
 51  Exter_Cond      2930 non-null   category
 52  Full_Bath       2930 non-null   category
 53  Utilities       2930 non-null   category
 54  Land_Contour    2930 non-null   category
dtypes: category(55)
memory usage: 162.4 KB

**Change data types of `categorical_features` to `category` for memory efficiency and better performance in modeling.**

In [182]:
for col in categorical_features_all:
    df[col] = df[col].astype('category')

In [183]:
df[categorical_features_all].info()

<class 'pandas.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 55 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Condition_1     2930 non-null   category
 1   MS_SubClass     2930 non-null   category
 2   Bsmt_Exposure   2847 non-null   category
 3   Paved_Drive     2930 non-null   category
 4   Electrical      2929 non-null   category
 5   Exter_Qual      2930 non-null   category
 6   Sale_Condition  2930 non-null   category
 7   Mas_Vnr_Type    1155 non-null   category
 8   Garage_Finish   2771 non-null   category
 9   Bsmt_Cond       2850 non-null   category
 10  Street          2930 non-null   category
 11  Bsmt_Full_Bath  2928 non-null   category
 12  Neighborhood    2930 non-null   category
 13  Foundation      2930 non-null   category
 14  Heating         2930 non-null   category
 15  Functional      2930 non-null   category
 16  Bedroom_AbvGr   2930 non-null   category
 17  Roof_Style      2930 non-null   category
 18  Roof_Matl       2930 non-null   category
 19  House_Style     2930 non-null   category
 20  Pool_QC         13 non-null     category
 21  Sale_Type       2930 non-null   category
 22  Kitchen_Qual    2930 non-null   category
 23  Lot_Config      2930 non-null   category
 24  Garage_Cars     2929 non-null   category
 25  Half_Bath       2930 non-null   category
 26  Overall_Qual    2930 non-null   category
 27  Bsmt_Qual       2850 non-null   category
 28  Land_Slope      2930 non-null   category
 29  Fence           572 non-null    category
 30  Overall_Cond    2930 non-null   category
 31  Bldg_Type       2930 non-null   category
 32  MS_Zoning       2930 non-null   category
 33  Condition_2     2930 non-null   category
 34  Fireplaces      2930 non-null   category
 35  BsmtFin_Type_1  2850 non-null   category
 36  Garage_Cond     2771 non-null   category
 37  Bsmt_Half_Bath  2928 non-null   category
 38  BsmtFin_Type_2  2849 non-null   category
 39  Garage_Qual     2771 non-null   category
 40  TotRms_AbvGrd   2930 non-null   category
 41  Central_Air     2930 non-null   category
 42  Exterior_2nd    2930 non-null   category
 43  Garage_Type     2773 non-null   category
 44  Fireplace_Qu    1508 non-null   category
 45  Lot_Shape       2930 non-null   category
 46  Exterior_1st    2930 non-null   category
 47  Kitchen_AbvGr   2930 non-null   category
 48  Heating_QC      2930 non-null   category
 49  Alley           198 non-null    category
 50  Misc_Feature    106 non-null    category
 51  Exter_Cond      2930 non-null   category
 52  Full_Bath       2930 non-null   category
 53  Utilities       2930 non-null   category
 54  Land_Contour    2930 non-null   category
dtypes: category(55)
memory usage: 162.4 KB

> Now data types of categorical features have been changed to `category`.

In [187]:
# Describe the categorical features
df[categorical_features_all].describe()

,Condition_1,MS_SubClass,Bsmt_Exposure,Paved_Drive,Electrical,Exter_Qual,Sale_Condition,Mas_Vnr_Type,Garage_Finish,Bsmt_Cond,...,Lot_Shape,Exterior_1st,Kitchen_AbvGr,Heating_QC,Alley,Misc_Feature,Exter_Cond,Full_Bath,Utilities,Land_Contour
count,2930,2930,2847,2930,2929,2930,2930,1155,2771,2850,...,2930,2930,2930,2930,198,106,2930,2930,2930,2930
unique,9,16,4,3,5,4,6,4,3,5,...,4,16,4,5,2,5,5,5,3,4
top,Norm,20,No,Y,SBrkr,TA,Normal,BrkFace,Unf,TA,...,Reg,VinylSd,1,Ex,Grvl,Shed,TA,2,AllPub,Lvl
freq,2522,1079,1906,2652,2682,1799,2413,880,1231,2616,...,1859,1026,2796,1495,120,95,2549,1532,2927,2633

**Exclude `SalePrice` from the list of numerical features.**

In [189]:
numerical_features = [col for col in numerical_features if col != 'SalePrice']
numerical_features

['MS_SubClass',
 'Lot_Frontage',
 'Lot_Area',
 'Overall_Qual',
 'Overall_Cond',
 'Year_Built',
 'Year_Remod/Add',
 'Mas_Vnr_Area',
 'BsmtFin_SF_1',
 'BsmtFin_SF_2',
 'Bsmt_Unf_SF',
 'Total_Bsmt_SF',
 '1st_Flr_SF',
 '2nd_Flr_SF',
 'Low_Qual_Fin_SF',
 'Gr_Liv_Area',
 'Bsmt_Full_Bath',
 'Bsmt_Half_Bath',
 'Full_Bath',
 'Half_Bath',
 'Bedroom_AbvGr',
 'Kitchen_AbvGr',
 'TotRms_AbvGrd',
 'Fireplaces',
 'Garage_Yr_Blt',
 'Garage_Cars',
 'Garage_Area',
 'Wood_Deck_SF',
 'Open_Porch_SF',
 'Enclosed_Porch',
 '3Ssn_Porch',
 'Screen_Porch',
 'Pool_Area',
 'Misc_Val',
 'Mo_Sold',
 'Yr_Sold']